### ISSUE TITLE
rolling update 임에도 불구하고 연결이 끊기는 오류.

### ISSUE THREAD

**Issue by dohyung97022** [dohyung97022/AWSLambdaClone#24]
pod 를 2개로 사용할 경우 해당 문제가 해결됨을 확인했습니다.
다만 memory 가 과도하게 사용됨을 고려해서 pod 를 1개로 유지하는 것이 좋을 것으로 보입니다.

신규 pod 가 생성될 때 pod 의 개수가 2개가 되고 ready 가 1개가 되어 모든 조건이 만족됨으로 k8s 에서 ready pod 를 삭제된다는 현상이 있습니다.
해당 현상과 일치한다면 다음을 추가하여 없앨 수도 있습니다.
https://stackoverflow.com/questions/46369100/kubernetes-rolling-update-killing-off-old-pod-without-bringing-up-new-one
```yaml
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
```
