### ISSUE TITLE
mongodb pod 의 DiskPressure attempting to reclaim ephemeral-storage 오류.

### ISSUE THREAD

**Issue by dohyung97022** [dohyung97022/AWSLambdaClone#9]
pod 내의 mongodb 가 node 의 DiskPressure 를 유발하는 오류.

"emptyDir, configMap, downwardAPI, secret are provided as [local ephemeral storage](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#local-ephemeral-storage)."
[k8s documentation](https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/)

"If you don't set limits.ephemeral-storage, requests.ephemeral-storage, by default pods have permission to use all node's storage space."
[stackoverflow](https://stackoverflow.com/questions/59906810/the-node-was-low-on-resource-ephemeral-storage)

```yaml
resources:
  requests:
    ephemeral-storage: "1Gi"
  limits:
    ephemeral-storage: "2Gi"
```
다음 방식으로 디스크 양을 제한합니다.
